"""empty message

Revision ID: 130cb1a2c6fb
Revises: 
Create Date: 2019-05-09 15:22:07.162482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130cb1a2c6fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(length=500), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
